[package]
name = "speedflow_hal"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = "0.14.0"

[build-dependencies]
cc = "1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
